/**
 * Seed script — loads a curated set of prestigious internship & graduate
 * programmes in Malaysia into the Postgres database (Neon).
 *
 * Requires the DATABASE_URL environment variable (your Neon connection
 * string). Locally it is read from .env.local automatically.
 *
 * Run with:  npm run seed          (adds only if empty)
 *            npm run seed -- --force  (wipes and reloads)
 *
 * ---------------------------------------------------------------------------
 * IMPORTANT — about the data
 * ---------------------------------------------------------------------------
 * These are REAL, well-known programmes at real employers operating in
 * Malaysia, with links to their official careers/programme pages. However,
 * the exact OPEN/CLOSE DATES are ESTIMATES based on typical annual cycles —
 * companies rarely publish next year's dates far in advance. The curator
 * (you, via the Admin panel) should confirm and adjust each date against the
 * official page. Statuses shown on the site are computed from these dates
 * relative to today, so keeping them current is what keeps the board useful.
 * ---------------------------------------------------------------------------
 */

import { Pool } from "pg";
import type { ProgramInput } from "../lib/types";

const FORCE = process.argv.includes("--force");

// ---------------------------------------------------------------------------
// Date helpers — anchor the seed's example cycle around "now" so the board
// shows a realistic mix of open / upcoming / closed on first load.
// ---------------------------------------------------------------------------
const iso = (d: Date) => d.toISOString().slice(0, 10);
const daysFromNow = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return iso(d);
};
const monthName = (offsetMonths: number) => {
  const d = new Date();
  d.setMonth(d.getMonth() + offsetMonths);
  return d.toLocaleDateString("en-GB", { month: "short", year: "numeric" });
};

type Seed = Omit<ProgramInput, "location"> & { location?: string };

const programs: Seed[] = [
  // ===================== INVESTMENT BANKING =====================
  {
    title: "2027 Asia Analyst Development Program — Summer Analyst",
    company: "J.P. Morgan",
    industry: "Investment Banking",
    roleType: "Internship",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-20),
    closeDate: daysFromNow(25),
    expectedReopen: null,
    applyLink:
      "https://careers.jpmorgan.com/global/en/students/programs",
    eligibility: "Penultimate-year undergraduates",
    notes: "9-week summer internship; pipeline into the full-time ADP rotational programme.",
  },
  {
    title: "Asia Analyst Development Program — Full Time",
    company: "J.P. Morgan",
    industry: "Investment Banking",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(11)}`,
    applyLink: "https://careers.jpmorgan.com/global/en/students/programs",
    eligibility: "Final-year students & fresh graduates",
    notes: "Rotational programme across front, middle and back office in the ASEAN franchise.",
  },
  {
    title: "Investment Banking Summer Analyst",
    company: "Goldman Sachs",
    industry: "Investment Banking",
    roleType: "Internship",
    location: "Singapore / SEA",
    openDate: daysFromNow(15),
    closeDate: daysFromNow(60),
    expectedReopen: null,
    applyLink: "https://www.goldmansachs.com/careers/students/programs",
    eligibility: "Penultimate-year undergraduates",
    notes: "Regional SEA intake; Malaysians frequently placed via Singapore hub.",
  },
  {
    title: "New Analyst Programme",
    company: "Morgan Stanley",
    industry: "Investment Banking",
    roleType: "Graduate Programme",
    location: "Singapore / SEA",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(10)}`,
    applyLink: "https://www.morganstanley.com/people-opportunities/students-graduates",
    eligibility: "Final-year students & fresh graduates",
    notes: "Regional APAC graduate intake.",
  },
  {
    title: "Global Markets Summer Analyst",
    company: "Citi",
    industry: "Investment Banking",
    roleType: "Internship",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-40),
    closeDate: daysFromNow(-5),
    expectedReopen: `Expected ${monthName(9)}`,
    applyLink: "https://www.citigroup.com/global/careers/students-and-graduates",
    eligibility: "Penultimate-year undergraduates",
    notes: "Citi has a large Kuala Lumpur hub (Citi Solutions Center).",
  },
  {
    title: "Graduate Analyst Programme",
    company: "Citi",
    industry: "Investment Banking",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-10),
    closeDate: daysFromNow(35),
    expectedReopen: null,
    applyLink: "https://www.citigroup.com/global/careers/students-and-graduates",
    eligibility: "Final-year students & fresh graduates",
    notes: null,
  },
  {
    title: "CIMB Internship Programme",
    company: "CIMB",
    industry: "Investment Banking",
    roleType: "Internship",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-120),
    closeDate: null,
    expectedReopen: null,
    applyLink: "https://www.cimb.com/en/careers/students/cimb-internship-programme.html",
    eligibility: "Undergraduates (apply 3 months before intended start)",
    notes: "Open all year round; rolling applications.",
  },
  {
    title: "The Complete Banker (TCB)",
    company: "CIMB",
    industry: "Investment Banking",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-6),
    closeDate: daysFromNow(40),
    expectedReopen: null,
    applyLink: "https://www.cimb.com/en/careers/fresh-graduate/the-complete-banker.html",
    eligibility: "Fresh graduates (all disciplines)",
    notes: "Flagship 2-year structured graduate programme across the banking group.",
  },
  {
    title: "Maybank GO Ahead. Challenge / Global Programme",
    company: "Maybank",
    industry: "Investment Banking",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(20),
    closeDate: daysFromNow(70),
    expectedReopen: null,
    applyLink: "https://www.maybank.com/en/careers.page",
    eligibility: "Final-year students & fresh graduates",
    notes: "Global case competition that fast-tracks winners into the graduate programme.",
  },
  {
    title: "Maybank Money Makers Internship",
    company: "Maybank",
    industry: "Investment Banking",
    roleType: "Internship",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-90),
    closeDate: null,
    expectedReopen: null,
    applyLink: "https://www.maybank.com/en/careers.page",
    eligibility: "Undergraduates",
    notes: "Rolling internship intake across the group.",
  },
  {
    title: "Wealth Graduate Programme",
    company: "HSBC",
    industry: "Investment Banking",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur / Klang Valley",
    openDate: daysFromNow(-3),
    closeDate: daysFromNow(45),
    expectedReopen: null,
    applyLink: "https://www.hsbc.com/careers/students-and-graduates/graduate-programmes",
    eligibility: "Fresh graduates",
    notes: "Develops participants into licensed Wealth Managers.",
  },
  {
    title: "HSBC Global Graduate Programme",
    company: "HSBC",
    industry: "Investment Banking",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(8)}`,
    applyLink: "https://www.hsbc.com/careers/students-and-graduates/graduate-programmes",
    eligibility: "Final-year students & fresh graduates",
    notes: "Multiple streams (Global Banking & Markets, Wealth & Personal Banking, etc.).",
  },
  {
    title: "HSBC Summer Internship",
    company: "HSBC",
    industry: "Investment Banking",
    roleType: "Internship",
    location: "Kuala Lumpur",
    openDate: daysFromNow(30),
    closeDate: daysFromNow(90),
    expectedReopen: null,
    applyLink: "https://www.hsbc.com/careers/students-and-graduates/internships",
    eligibility: "Penultimate-year students",
    notes: null,
  },
  {
    title: "International Graduate Programme",
    company: "Standard Chartered",
    industry: "Investment Banking",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(10),
    closeDate: daysFromNow(65),
    expectedReopen: null,
    applyLink: "https://www.sc.com/en/careers/students-and-graduates/",
    eligibility: "Final-year students & fresh graduates",
    notes: "Streams across Corporate & Investment Banking, Consumer Banking, Functions.",
  },
  {
    title: "SC Ready Internship Programme",
    company: "Standard Chartered",
    industry: "Investment Banking",
    roleType: "Internship",
    location: "Kuala Lumpur",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(7)}`,
    applyLink: "https://www.sc.com/en/careers/students-and-graduates/",
    eligibility: "Penultimate-year students",
    notes: null,
  },
  {
    title: "Deutsche Bank Graduate Programme",
    company: "Deutsche Bank",
    industry: "Investment Banking",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(9)}`,
    applyLink: "https://careers.db.com/students-graduates/",
    eligibility: "Final-year students & fresh graduates",
    notes: "DB operates a technology & operations centre in Kuala Lumpur.",
  },
  {
    title: "UBS Graduate Talent Program",
    company: "UBS",
    industry: "Investment Banking",
    roleType: "Graduate Programme",
    location: "Singapore / SEA",
    openDate: daysFromNow(5),
    closeDate: daysFromNow(50),
    expectedReopen: null,
    applyLink: "https://www.ubs.com/global/en/careers/students-graduates.html",
    eligibility: "Final-year students & fresh graduates",
    notes: "Regional APAC intake.",
  },

  // ===================== CONSULTING =====================
  {
    title: "Business Analyst",
    company: "McKinsey & Company",
    industry: "Consulting",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-12),
    closeDate: daysFromNow(30),
    expectedReopen: null,
    applyLink: "https://www.mckinsey.com/my/careers",
    eligibility: "Final-year students & fresh graduates (all disciplines)",
    notes: "Entry-level consulting role; strong pathway to Associate.",
  },
  {
    title: "Summer Business Analyst Internship",
    company: "McKinsey & Company",
    industry: "Consulting",
    roleType: "Internship",
    location: "Kuala Lumpur",
    openDate: daysFromNow(25),
    closeDate: daysFromNow(75),
    expectedReopen: null,
    applyLink: "https://www.mckinsey.com/my/careers",
    eligibility: "Penultimate-year students",
    notes: null,
  },
  {
    title: "Associate Consultant",
    company: "Bain & Company",
    industry: "Consulting",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(8)}`,
    applyLink: "https://www.bain.com/careers/",
    eligibility: "Final-year students & fresh graduates",
    notes: "SEA intake; KL office serves regional clients.",
  },
  {
    title: "Associate Consultant Intern (ACI)",
    company: "Bain & Company",
    industry: "Consulting",
    roleType: "Internship",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-30),
    closeDate: daysFromNow(-2),
    expectedReopen: `Expected ${monthName(10)}`,
    applyLink: "https://www.bain.com/careers/",
    eligibility: "Penultimate-year students",
    notes: null,
  },
  {
    title: "Associate",
    company: "Boston Consulting Group (BCG)",
    industry: "Consulting",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-8),
    closeDate: daysFromNow(28),
    expectedReopen: null,
    applyLink: "https://careers.bcg.com/",
    eligibility: "Final-year students & fresh graduates",
    notes: null,
  },
  {
    title: "Summer Associate Internship",
    company: "Boston Consulting Group (BCG)",
    industry: "Consulting",
    roleType: "Internship",
    location: "Kuala Lumpur",
    openDate: daysFromNow(35),
    closeDate: daysFromNow(85),
    expectedReopen: null,
    applyLink: "https://careers.bcg.com/",
    eligibility: "Penultimate-year students",
    notes: null,
  },
  {
    title: "Analyst — Strategy & Consulting",
    company: "Accenture",
    industry: "Consulting",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-60),
    closeDate: null,
    expectedReopen: null,
    applyLink: "https://www.accenture.com/my-en/careers",
    eligibility: "Fresh graduates",
    notes: "Rolling intake across Strategy, Technology, and Operations.",
  },
  {
    title: "Roland Berger Junior Consultant",
    company: "Roland Berger",
    industry: "Consulting",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(6)}`,
    applyLink: "https://www.rolandberger.com/en/Career/",
    eligibility: "Fresh graduates",
    notes: null,
  },

  // ===================== PROFESSIONAL SERVICES (BIG 4) =====================
  {
    title: "Deloitte Amplify Internship Programme",
    company: "Deloitte",
    industry: "Professional Services",
    roleType: "Internship",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-15),
    closeDate: daysFromNow(20),
    expectedReopen: null,
    applyLink:
      "https://www.deloitte.com/southeast-asia/en/careers/explore-your-fit/students/amplify-programme.html",
    eligibility: "Undergraduates (penultimate/final year)",
    notes: "12-week internship; intakes typically Mar/Apr and Sep.",
  },
  {
    title: "Audit & Assurance Associate",
    company: "Deloitte",
    industry: "Professional Services",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-70),
    closeDate: null,
    expectedReopen: null,
    applyLink: "https://jobs.sea.deloitte.com/go/Students/4636010/",
    eligibility: "Fresh graduates (Accounting/Finance)",
    notes: "Rolling graduate intake.",
  },
  {
    title: "Associate — Audit Assurance (Nov 2026 Intake)",
    company: "PwC",
    industry: "Professional Services",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-5),
    closeDate: daysFromNow(30),
    expectedReopen: null,
    applyLink: "https://www.pwc.com/my/en/careers/graduates-non-graduates/job-search.html",
    eligibility: "Fresh graduates (Accounting/Finance)",
    notes: "PwC posts multiple dated intakes throughout the year.",
  },
  {
    title: "PwC Internship / Student Programme",
    company: "PwC",
    industry: "Professional Services",
    roleType: "Internship",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-100),
    closeDate: null,
    expectedReopen: null,
    applyLink: "https://www.pwc.com/my/en/careers/graduates-non-graduates/job-search.html",
    eligibility: "Undergraduates",
    notes: "Rolling; internships across Assurance, Tax, Advisory.",
  },
  {
    title: "Agile Tax Professional (ATP) Programme",
    company: "PwC",
    industry: "Professional Services",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-4),
    closeDate: daysFromNow(38),
    expectedReopen: null,
    applyLink: "https://www.pwc.com/my/en/careers/graduates-non-graduates/job-search.html",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "KPMG Graduate Recruitment",
    company: "KPMG",
    industry: "Professional Services",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-25),
    closeDate: daysFromNow(15),
    expectedReopen: null,
    applyLink: "https://kpmg.com/my/en/careers/graduates.html",
    eligibility: "Fresh graduates",
    notes: "Audit, Tax and Advisory streams.",
  },
  {
    title: "KPMG Internship Programme",
    company: "KPMG",
    industry: "Professional Services",
    roleType: "Internship",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-110),
    closeDate: null,
    expectedReopen: null,
    applyLink: "https://kpmg.com/my/en/careers/graduates.html",
    eligibility: "Undergraduates",
    notes: "Rolling intake.",
  },
  {
    title: "EY Graduate Programme",
    company: "EY (Ernst & Young)",
    industry: "Professional Services",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(6)}`,
    applyLink: "https://www.ey.com/en_my/careers",
    eligibility: "Fresh graduates",
    notes: "Assurance, Consulting, Strategy & Transactions, Tax.",
  },
  {
    title: "EY Internship Programme",
    company: "EY (Ernst & Young)",
    industry: "Professional Services",
    roleType: "Internship",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-95),
    closeDate: null,
    expectedReopen: null,
    applyLink: "https://www.ey.com/en_my/careers",
    eligibility: "Undergraduates",
    notes: "Rolling intake.",
  },

  // ===================== FMCG =====================
  {
    title: "Nestlé Management Trainee Programme",
    company: "Nestlé",
    industry: "FMCG",
    roleType: "Management Trainee",
    location: "Petaling Jaya, Selangor",
    openDate: daysFromNow(-7),
    closeDate: daysFromNow(35),
    expectedReopen: null,
    applyLink: "https://www.nestle.com.my/jobs/students-graduates",
    eligibility: "Fresh graduates (<2 years experience)",
    notes: "2-year rotational programme across the value chain.",
  },
  {
    title: "Nestlé Supply Chain Management Trainee",
    company: "Nestlé",
    industry: "FMCG",
    roleType: "Management Trainee",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-7),
    closeDate: daysFromNow(35),
    expectedReopen: null,
    applyLink: "https://jobdetails.nestle.com/",
    eligibility: "Fresh graduates",
    notes: "Focus on planning & supply-chain analytics.",
  },
  {
    title: "Nestlé Internship Programme",
    company: "Nestlé",
    industry: "FMCG",
    roleType: "Internship",
    location: "Petaling Jaya, Selangor",
    openDate: daysFromNow(-80),
    closeDate: null,
    expectedReopen: null,
    applyLink: "https://www.nestle.com.my/jobs/students-graduates",
    eligibility: "Undergraduates",
    notes: "Rolling intake.",
  },
  {
    title: "Unilever Future Leaders Programme (UFLP)",
    company: "Unilever",
    industry: "FMCG",
    roleType: "Management Trainee",
    location: "Bangsar South, Kuala Lumpur",
    openDate: daysFromNow(12),
    closeDate: daysFromNow(55),
    expectedReopen: null,
    applyLink: "https://careers.unilever.com/unilever-future-leaders-programme",
    eligibility: "Fresh graduates",
    notes: "Flagship ~3-year leadership programme; choose a functional track.",
  },
  {
    title: "Unilever Marketing Young Manager Programme",
    company: "Unilever",
    industry: "FMCG",
    roleType: "Management Trainee",
    location: "Kuala Lumpur",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(5)}`,
    applyLink: "https://careers.unilever.com/en/malaysia",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "Unilever Internship (Future Leaders League)",
    company: "Unilever",
    industry: "FMCG",
    roleType: "Internship",
    location: "Kuala Lumpur",
    openDate: daysFromNow(40),
    closeDate: daysFromNow(90),
    expectedReopen: null,
    applyLink: "https://careers.unilever.com/en/malaysia",
    eligibility: "Penultimate-year students",
    notes: null,
  },
  {
    title: "P&G Management Trainee (various functions)",
    company: "Procter & Gamble",
    industry: "FMCG",
    roleType: "Management Trainee",
    location: "Petaling Jaya, Selangor",
    openDate: daysFromNow(-2),
    closeDate: daysFromNow(42),
    expectedReopen: null,
    applyLink: "https://www.pgcareers.com/",
    eligibility: "Fresh graduates",
    notes: "Hire-from-within culture; functional entry (Brand, Finance, Sales, Supply).",
  },
  {
    title: "P&G Internship Programme",
    company: "Procter & Gamble",
    industry: "FMCG",
    roleType: "Internship",
    location: "Petaling Jaya, Selangor",
    openDate: daysFromNow(-50),
    closeDate: daysFromNow(-10),
    expectedReopen: `Expected ${monthName(9)}`,
    applyLink: "https://www.pgcareers.com/",
    eligibility: "Penultimate-year students",
    notes: null,
  },
  {
    title: "L'Oréal Management Trainee Programme",
    company: "L'Oréal",
    industry: "FMCG",
    roleType: "Management Trainee",
    location: "Kuala Lumpur",
    openDate: daysFromNow(8),
    closeDate: daysFromNow(48),
    expectedReopen: null,
    applyLink: "https://careers.loreal.com/en_US/content/Malaysia",
    eligibility: "Fresh graduates",
    notes: "Rotations across functions, up to ~18 months.",
  },
  {
    title: "L'Oréal Internship Programme",
    company: "L'Oréal",
    industry: "FMCG",
    roleType: "Internship",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-85),
    closeDate: null,
    expectedReopen: null,
    applyLink: "https://careers.loreal.com/en_US/content/Students",
    eligibility: "Undergraduates",
    notes: "Interns often converted to Management Trainee.",
  },
  {
    title: "BAT Global Graduate Programme",
    company: "British American Tobacco",
    industry: "FMCG",
    roleType: "Management Trainee",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-9),
    closeDate: daysFromNow(33),
    expectedReopen: null,
    applyLink: "https://careers.bat.com/global-graduate-programme",
    eligibility: "Fresh graduates",
    notes: "12-month accelerated leadership programme by function.",
  },
  {
    title: "Coca-Cola Management Trainee",
    company: "Coca-Cola",
    industry: "FMCG",
    roleType: "Management Trainee",
    location: "Kuala Lumpur",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(7)}`,
    applyLink: "https://www.coca-colacompany.com/careers",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "Mondelēz Management Associate Programme (MAP)",
    company: "Mondelēz International",
    industry: "FMCG",
    roleType: "Management Associate",
    location: "Kuala Lumpur",
    openDate: daysFromNow(18),
    closeDate: daysFromNow(60),
    expectedReopen: null,
    applyLink: "https://www.mondelezinternational.com/careers/",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "Reckitt Management Trainee Programme",
    company: "Reckitt",
    industry: "FMCG",
    roleType: "Management Trainee",
    location: "Kuala Lumpur",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(6)}`,
    applyLink: "https://careers.reckitt.com/",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "Dyson Graduate Programme",
    company: "Dyson",
    industry: "FMCG",
    roleType: "Graduate Programme",
    location: "Johor / Kuala Lumpur",
    openDate: daysFromNow(-6),
    closeDate: daysFromNow(36),
    expectedReopen: null,
    applyLink: "https://careers.dyson.com/en-gb/early-careers/",
    eligibility: "Fresh graduates (Engineering/Tech focus)",
    notes: "Dyson has major operations & development centres in Malaysia.",
  },

  // ===================== BIG TECH =====================
  {
    title: "Software Engineering Internship",
    company: "Google",
    industry: "Big Tech",
    roleType: "Internship",
    location: "Kuala Lumpur",
    openDate: daysFromNow(22),
    closeDate: daysFromNow(70),
    expectedReopen: null,
    applyLink: "https://www.google.com/about/careers/applications/students/",
    eligibility: "Undergraduates in CS/related",
    notes: "APAC intake; strong conversion to full-time.",
  },
  {
    title: "Associate Product Manager (APM)",
    company: "Google",
    industry: "Big Tech",
    roleType: "Graduate Programme",
    location: "Singapore / APAC",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(9)}`,
    applyLink: "https://www.google.com/about/careers/applications/students/",
    eligibility: "Final-year students & fresh graduates",
    notes: "Highly selective rotational PM programme.",
  },
  {
    title: "Microsoft Aspire / New-grad SWE",
    company: "Microsoft",
    industry: "Big Tech",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-11),
    closeDate: daysFromNow(29),
    expectedReopen: null,
    applyLink: "https://careers.microsoft.com/students/",
    eligibility: "Fresh graduates",
    notes: "Aspire onboarding programme for early-career hires.",
  },
  {
    title: "Microsoft Internship Programme",
    company: "Microsoft",
    industry: "Big Tech",
    roleType: "Internship",
    location: "Kuala Lumpur",
    openDate: daysFromNow(28),
    closeDate: daysFromNow(80),
    expectedReopen: null,
    applyLink: "https://careers.microsoft.com/students/",
    eligibility: "Undergraduates",
    notes: null,
  },
  {
    title: "Intel Malaysia College Graduate Programme",
    company: "Intel",
    industry: "Big Tech",
    roleType: "Graduate Programme",
    location: "Penang / Kulim",
    openDate: daysFromNow(-14),
    closeDate: daysFromNow(30),
    expectedReopen: null,
    applyLink: "https://jobs.intel.com/",
    eligibility: "Fresh graduates (Engineering)",
    notes: "Intel's largest site outside the US is in Malaysia.",
  },
  {
    title: "Intel Internship Programme",
    company: "Intel",
    industry: "Big Tech",
    roleType: "Internship",
    location: "Penang",
    openDate: daysFromNow(-75),
    closeDate: null,
    expectedReopen: null,
    applyLink: "https://jobs.intel.com/",
    eligibility: "Undergraduates (Engineering)",
    notes: "Rolling intake.",
  },
  {
    title: "AMD Graduate Engineer Programme",
    company: "AMD",
    industry: "Big Tech",
    roleType: "Graduate Programme",
    location: "Penang / Cyberjaya",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(5)}`,
    applyLink: "https://www.amd.com/en/corporate/careers/university.html",
    eligibility: "Fresh graduates (Engineering)",
    notes: null,
  },
  {
    title: "Grab Kickstart Internship",
    company: "Grab",
    industry: "Big Tech",
    roleType: "Internship",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-1),
    closeDate: daysFromNow(44),
    expectedReopen: null,
    applyLink: "https://grab.careers/students/",
    eligibility: "Penultimate/final-year students",
    notes: "Grab runs a major R&D centre in Malaysia.",
  },
  {
    title: "Grab MEX (Management Associate) Programme",
    company: "Grab",
    industry: "Big Tech",
    roleType: "Management Associate",
    location: "Kuala Lumpur",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(8)}`,
    applyLink: "https://grab.careers/",
    eligibility: "Fresh graduates",
    notes: "Rotational leadership associate programme.",
  },
  {
    title: "Shopee & Monee Graduate Development Programme (GDP)",
    company: "Shopee",
    industry: "Big Tech",
    roleType: "Management Associate",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-13),
    closeDate: daysFromNow(27),
    expectedReopen: null,
    applyLink: "https://careers.shopee.com.my/",
    eligibility: "Fresh graduates",
    notes: "2-year management associate programme across business functions.",
  },
  {
    title: "Shopee Internship Programme",
    company: "Shopee",
    industry: "Big Tech",
    roleType: "Internship",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-65),
    closeDate: null,
    expectedReopen: null,
    applyLink: "https://careers.shopee.com.my/",
    eligibility: "Undergraduates",
    notes: "Rolling intake.",
  },
  {
    title: "TikTok Graduate / Campus Recruitment",
    company: "TikTok",
    industry: "Big Tech",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(16),
    closeDate: daysFromNow(58),
    expectedReopen: null,
    applyLink: "https://careers.tiktok.com/position?type=3",
    eligibility: "Final-year students & fresh graduates",
    notes: null,
  },
  {
    title: "AWS Malaysia Early Careers",
    company: "Amazon Web Services",
    industry: "Big Tech",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur / Cyberjaya",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(7)}`,
    applyLink: "https://www.amazon.jobs/en/teams/internships-for-students",
    eligibility: "Fresh graduates",
    notes: "AWS is building out its Malaysia cloud region.",
  },

  // ===================== OIL & GAS =====================
  {
    title: "PETRONAS Graduate Employability Programme",
    company: "PETRONAS",
    industry: "Oil & Gas",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-16),
    closeDate: daysFromNow(24),
    expectedReopen: null,
    applyLink: "https://www.petronas.com/careers",
    eligibility: "Fresh graduates",
    notes: "National oil company; premier employer for engineering & business grads.",
  },
  {
    title: "PETRONAS Internship (INSTEP / Sponsored)",
    company: "PETRONAS",
    industry: "Oil & Gas",
    roleType: "Internship",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-70),
    closeDate: null,
    expectedReopen: null,
    applyLink: "https://www.petronas.com/careers",
    eligibility: "Undergraduates",
    notes: "Rolling intake.",
  },
  {
    title: "Shell Graduate Programme",
    company: "Shell",
    industry: "Oil & Gas",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur / Cyberjaya",
    openDate: daysFromNow(3),
    closeDate: daysFromNow(52),
    expectedReopen: null,
    applyLink: "https://www.shell.com/careers/students-and-graduates.html",
    eligibility: "Fresh graduates",
    notes: "Shell Business Operations & technical streams.",
  },
  {
    title: "Shell Internship / Assessed Internship",
    company: "Shell",
    industry: "Oil & Gas",
    roleType: "Internship",
    location: "Cyberjaya",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(6)}`,
    applyLink: "https://www.shell.com/careers/students-and-graduates.html",
    eligibility: "Penultimate-year students",
    notes: "Assessed internship can lead to a graduate offer.",
  },
  {
    title: "ExxonMobil Graduate Programme",
    company: "ExxonMobil",
    industry: "Oil & Gas",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-45),
    closeDate: null,
    expectedReopen: null,
    applyLink: "https://careers.exxonmobil.com/",
    eligibility: "Fresh graduates",
    notes: "Rolling intake across business & technical functions.",
  },
  {
    title: "Schlumberger (SLB) Graduate Hire",
    company: "SLB",
    industry: "Oil & Gas",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(5)}`,
    applyLink: "https://careers.slb.com/students",
    eligibility: "Fresh graduates (Engineering)",
    notes: null,
  },

  // ===================== MANAGEMENT TRAINEE (CONGLOMERATES) =====================
  {
    title: "Sime Darby Management Trainee Programme",
    company: "Sime Darby",
    industry: "Management Trainee",
    roleType: "Management Trainee",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-10),
    closeDate: daysFromNow(32),
    expectedReopen: null,
    applyLink: "https://www.simedarby.com/careers",
    eligibility: "Fresh graduates",
    notes: "Malaysian multinational conglomerate (industrial, motors, logistics).",
  },
  {
    title: "Sime Darby Plantation Graduate Programme",
    company: "SD Guthrie (Sime Darby Plantation)",
    industry: "Management Trainee",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(6)}`,
    applyLink: "https://www.sdguthrie.com/careers",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "YTL Group Management Trainee",
    company: "YTL Corporation",
    industry: "Management Trainee",
    roleType: "Management Trainee",
    location: "Kuala Lumpur",
    openDate: daysFromNow(14),
    closeDate: daysFromNow(56),
    expectedReopen: null,
    applyLink: "https://www.ytl.com/careers.asp",
    eligibility: "Fresh graduates",
    notes: "Utilities, construction, cement, digital (YTL Communications).",
  },
  {
    title: "Genting Management Trainee Programme",
    company: "Genting",
    industry: "Management Trainee",
    roleType: "Management Trainee",
    location: "Genting Highlands / KL",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(7)}`,
    applyLink: "https://www.rwgenting.com/careers/",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "IOI Group Management Trainee",
    company: "IOI Corporation",
    industry: "Management Trainee",
    roleType: "Management Trainee",
    location: "Putrajaya",
    openDate: daysFromNow(-55),
    closeDate: null,
    expectedReopen: null,
    applyLink: "https://www.ioigroup.com/Content/C/C_Career",
    eligibility: "Fresh graduates",
    notes: "Rolling intake.",
  },
  {
    title: "Axiata Young Talent Programme (AYTP)",
    company: "Axiata Group",
    industry: "Management Trainee",
    roleType: "Management Trainee",
    location: "Kuala Lumpur",
    openDate: daysFromNow(9),
    closeDate: daysFromNow(49),
    expectedReopen: null,
    applyLink: "https://www.axiata.com/careers",
    eligibility: "Fresh graduates",
    notes: "Regional telco conglomerate leadership programme.",
  },
  {
    title: "Khazanah / Nasional Berhad Graduate Programme",
    company: "Khazanah Nasional",
    industry: "Management Trainee",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(8)}`,
    applyLink: "https://www.khazanah.com.my/careers/",
    eligibility: "Fresh graduates & young professionals",
    notes: "Malaysia's sovereign wealth fund.",
  },
  {
    title: "PNB Future Leaders Programme",
    company: "Permodalan Nasional Berhad (PNB)",
    industry: "Management Trainee",
    roleType: "Management Trainee",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-8),
    closeDate: daysFromNow(34),
    expectedReopen: null,
    applyLink: "https://www.pnb.com.my/career.php",
    eligibility: "Fresh graduates",
    notes: null,
  },

  // ===================== INSURANCE & ASSET MANAGEMENT =====================
  {
    title: "Great Eastern Management Associate Programme",
    company: "Great Eastern",
    industry: "Insurance & Asset Management",
    roleType: "Management Associate",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-9),
    closeDate: daysFromNow(31),
    expectedReopen: null,
    applyLink: "https://www.greateasternlife.com/my/en/about-us/careers.html",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "Prudential Management Associate Programme (PMAP)",
    company: "Prudential",
    industry: "Insurance & Asset Management",
    roleType: "Management Associate",
    location: "Kuala Lumpur",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(7)}`,
    applyLink: "https://www.prudential.com.my/en/about-us/careers/",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "AIA Management Associate Programme",
    company: "AIA",
    industry: "Insurance & Asset Management",
    roleType: "Management Associate",
    location: "Kuala Lumpur",
    openDate: daysFromNow(20),
    closeDate: daysFromNow(62),
    expectedReopen: null,
    applyLink: "https://www.aia.com.my/en/careers.html",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "Allianz Graduate Programme",
    company: "Allianz",
    industry: "Insurance & Asset Management",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-30),
    closeDate: daysFromNow(-3),
    expectedReopen: `Expected ${monthName(9)}`,
    applyLink: "https://careers.allianz.com/",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "Manulife Management Trainee",
    company: "Manulife",
    industry: "Insurance & Asset Management",
    roleType: "Management Trainee",
    location: "Kuala Lumpur",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(6)}`,
    applyLink: "https://www.manulife.com.my/en/about-us/careers.html",
    eligibility: "Fresh graduates",
    notes: null,
  },

  // ===================== BANKING (RETAIL/COMMERCIAL) — MANAGEMENT ASSOCIATE =====================
  {
    title: "Hong Leong Bank Management Associate Programme",
    company: "Hong Leong Bank",
    industry: "Management Trainee",
    roleType: "Management Associate",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-4),
    closeDate: daysFromNow(40),
    expectedReopen: null,
    applyLink: "https://www.hlb.com.my/en/personal-banking/about-us/careers/management-associate-program.html",
    eligibility: "Fresh graduates",
    notes: "Cross-functional rotations + formal banking fundamentals training.",
  },
  {
    title: "Hong Leong Bank Graduate Trainee (GT)",
    company: "Hong Leong Bank",
    industry: "Management Trainee",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-60),
    closeDate: null,
    expectedReopen: null,
    applyLink: "https://www.hlb.com.my/en/personal-banking/about-us/careers.html",
    eligibility: "Fresh graduates",
    notes: "Division-specific graduate trainee tracks; rolling.",
  },
  {
    title: "Public Bank Management Trainee",
    company: "Public Bank",
    industry: "Management Trainee",
    roleType: "Management Trainee",
    location: "Kuala Lumpur",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(5)}`,
    applyLink: "https://www.pbebank.com/en/careers.html",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "RHB Management Associate Programme",
    company: "RHB Banking Group",
    industry: "Management Trainee",
    roleType: "Management Associate",
    location: "Kuala Lumpur",
    openDate: daysFromNow(11),
    closeDate: daysFromNow(53),
    expectedReopen: null,
    applyLink: "https://www.rhbgroup.com/others/career/index.html",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "AmBank Graduate Trainee Programme",
    company: "AmBank Group",
    industry: "Management Trainee",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(8)}`,
    applyLink: "https://www.ambankgroup.com/eng/Careers/",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "OCBC Graduate Talent Programme",
    company: "OCBC",
    industry: "Management Trainee",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(6),
    closeDate: daysFromNow(46),
    expectedReopen: null,
    applyLink: "https://www.ocbc.com.my/group/careers/index.html",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "UOB Management Associate Programme",
    company: "UOB",
    industry: "Management Trainee",
    roleType: "Management Associate",
    location: "Kuala Lumpur",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(7)}`,
    applyLink: "https://www.uob.com.my/careers/index.page",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "Bank Negara Malaysia Kijang Emas Scholarship / Graduate",
    company: "Bank Negara Malaysia",
    industry: "Management Trainee",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-35),
    closeDate: daysFromNow(-8),
    expectedReopen: `Expected ${monthName(10)}`,
    applyLink: "https://www.bnm.gov.my/careers",
    eligibility: "Fresh graduates & students",
    notes: "Central bank; highly selective.",
  },

  // ===================== TELECOMMUNICATIONS =====================
  {
    title: "Maxis Graduate Programme",
    company: "Maxis",
    industry: "Telecommunications",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-2),
    closeDate: daysFromNow(43),
    expectedReopen: null,
    applyLink: "https://www.maxis.com.my/en/about-maxis/career/maxis-graduate-programme/",
    eligibility: "Fresh graduates",
    notes: "Structured 2-year journey with cross-functional rotations.",
  },
  {
    title: "CelcomDigi Future Leaders Programme",
    company: "CelcomDigi",
    industry: "Telecommunications",
    roleType: "Management Trainee",
    location: "Kuala Lumpur",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(6)}`,
    applyLink: "https://www.celcomdigi.com/careers",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "TM Young Innovators / Graduate Programme",
    company: "Telekom Malaysia (TM)",
    industry: "Telecommunications",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(15),
    closeDate: daysFromNow(57),
    expectedReopen: null,
    applyLink: "https://www.tm.com.my/careers",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "U Mobile Graduate Programme",
    company: "U Mobile",
    industry: "Telecommunications",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-58),
    closeDate: null,
    expectedReopen: null,
    applyLink: "https://www.u.com.my/careers",
    eligibility: "Fresh graduates",
    notes: "Rolling intake.",
  },

  // ===================== AVIATION =====================
  {
    title: "AirAsia Allstar Graduate Programme",
    company: "AirAsia (Capital A)",
    industry: "Aviation",
    roleType: "Graduate Programme",
    location: "Sepang, Selangor",
    openDate: daysFromNow(-6),
    closeDate: daysFromNow(38),
    expectedReopen: null,
    applyLink: "https://careers.airasia.com/",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "Malaysia Airlines Graduate Trainee Programme",
    company: "Malaysia Airlines",
    industry: "Aviation",
    roleType: "Graduate Programme",
    location: "Sepang, Selangor",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(7)}`,
    applyLink: "https://www.malaysiaairlines.com/my/en/about-us/careers.html",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "Malaysia Airports Management Trainee",
    company: "Malaysia Airports Holdings",
    industry: "Aviation",
    roleType: "Management Trainee",
    location: "Sepang, Selangor",
    openDate: daysFromNow(19),
    closeDate: daysFromNow(61),
    expectedReopen: null,
    applyLink: "https://www.malaysiaairports.com.my/careers",
    eligibility: "Fresh graduates",
    notes: null,
  },

  // ===================== MORE BIG TECH / SEMICONDUCTOR =====================
  {
    title: "Micron Graduate Development Programme",
    company: "Micron",
    industry: "Big Tech",
    roleType: "Graduate Programme",
    location: "Batu Kawan, Penang",
    openDate: daysFromNow(-12),
    closeDate: daysFromNow(30),
    expectedReopen: null,
    applyLink: "https://careers.micron.com/careers/students-and-recent-grads",
    eligibility: "Fresh graduates (Engineering)",
    notes: "Major memory-manufacturing site in Penang.",
  },
  {
    title: "Western Digital Graduate Engineer",
    company: "Western Digital",
    industry: "Big Tech",
    roleType: "Graduate Programme",
    location: "Petaling Jaya / Penang",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(6)}`,
    applyLink: "https://jobs.smartrecruiters.com/WesternDigital/",
    eligibility: "Fresh graduates (Engineering)",
    notes: null,
  },
  {
    title: "Infineon Graduate Programme",
    company: "Infineon Technologies",
    industry: "Big Tech",
    roleType: "Graduate Programme",
    location: "Kulim / Melaka",
    openDate: daysFromNow(7),
    closeDate: daysFromNow(50),
    expectedReopen: null,
    applyLink: "https://www.infineon.com/cms/en/careers/students/",
    eligibility: "Fresh graduates (Engineering)",
    notes: null,
  },
  {
    title: "Keysight Early Careers Programme",
    company: "Keysight Technologies",
    industry: "Big Tech",
    roleType: "Graduate Programme",
    location: "Penang",
    openDate: daysFromNow(-52),
    closeDate: null,
    expectedReopen: null,
    applyLink: "https://careers.keysight.com/",
    eligibility: "Fresh graduates (Engineering)",
    notes: "Rolling intake.",
  },
  {
    title: "Bosch Graduate Specialist Programme (GSP)",
    company: "Bosch",
    industry: "Big Tech",
    roleType: "Graduate Programme",
    location: "Penang",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(5)}`,
    applyLink: "https://www.bosch.com.my/careers/",
    eligibility: "Fresh graduates (Engineering)",
    notes: null,
  },
  {
    title: "Intel Internship for Malaysian Students (Business)",
    company: "Intel",
    industry: "Big Tech",
    roleType: "Internship",
    location: "Penang / Kulim",
    openDate: daysFromNow(23),
    closeDate: daysFromNow(72),
    expectedReopen: null,
    applyLink: "https://jobs.intel.com/",
    eligibility: "Undergraduates (Business/Finance)",
    notes: null,
  },
  {
    title: "Lazada Management Associate Programme",
    company: "Lazada",
    industry: "Big Tech",
    roleType: "Management Associate",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-9),
    closeDate: daysFromNow(31),
    expectedReopen: null,
    applyLink: "https://www.lazada.com/en/careers/",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "Sea / Garena Global Leaders Programme",
    company: "Sea Group",
    industry: "Big Tech",
    roleType: "Management Associate",
    location: "Kuala Lumpur / Singapore",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(8)}`,
    applyLink: "https://career.sea.com/",
    eligibility: "Fresh graduates",
    notes: null,
  },

  // ===================== HEALTHCARE / PHARMA (FMCG-adjacent) =====================
  {
    title: "Roche Graduate Programme",
    company: "Roche",
    industry: "FMCG",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(4),
    closeDate: daysFromNow(47),
    expectedReopen: null,
    applyLink: "https://careers.roche.com/global/en/students-graduates",
    eligibility: "Fresh graduates",
    notes: "Pharma & diagnostics; commercial and technical tracks.",
  },
  {
    title: "GSK Future Leaders Programme",
    company: "GSK",
    industry: "FMCG",
    roleType: "Management Trainee",
    location: "Petaling Jaya, Selangor",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(6)}`,
    applyLink: "https://www.gsk.com/en-gb/careers/early-talent/",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "Sanofi iMove / Graduate Programme",
    company: "Sanofi",
    industry: "FMCG",
    roleType: "Graduate Programme",
    location: "Petaling Jaya, Selangor",
    openDate: daysFromNow(-40),
    closeDate: daysFromNow(-5),
    expectedReopen: `Expected ${monthName(9)}`,
    applyLink: "https://www.sanofi.com/en/careers",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "IHH Healthcare Management Trainee",
    company: "IHH Healthcare",
    industry: "Management Trainee",
    roleType: "Management Trainee",
    location: "Kuala Lumpur",
    openDate: daysFromNow(13),
    closeDate: daysFromNow(55),
    expectedReopen: null,
    applyLink: "https://www.ihhhealthcare.com/careers",
    eligibility: "Fresh graduates",
    notes: "Operator of Pantai & Gleneagles hospitals.",
  },

  // ===================== LOGISTICS / INDUSTRIAL =====================
  {
    title: "DHL Graduate Programme (GROW)",
    company: "DHL",
    industry: "Management Trainee",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-7),
    closeDate: daysFromNow(35),
    expectedReopen: null,
    applyLink: "https://careers.dhl.com/global/en/students",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "Schneider Electric Graduate Programme",
    company: "Schneider Electric",
    industry: "Management Trainee",
    roleType: "Graduate Programme",
    location: "Petaling Jaya, Selangor",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(7)}`,
    applyLink: "https://www.se.com/ww/en/about-us/careers/",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "Gamuda Scholar / Graduate Programme",
    company: "Gamuda",
    industry: "Management Trainee",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(10),
    closeDate: daysFromNow(52),
    expectedReopen: null,
    applyLink: "https://gamuda.com.my/careers/",
    eligibility: "Fresh graduates (Engineering/Business)",
    notes: null,
  },
  {
    title: "IJM Management Trainee",
    company: "IJM Corporation",
    industry: "Management Trainee",
    roleType: "Management Trainee",
    location: "Petaling Jaya, Selangor",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(6)}`,
    applyLink: "https://www.ijm.com/careers",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "Sunway Group Management Trainee",
    company: "Sunway Group",
    industry: "Management Trainee",
    roleType: "Management Trainee",
    location: "Bandar Sunway, Selangor",
    openDate: daysFromNow(-3),
    closeDate: daysFromNow(41),
    expectedReopen: null,
    applyLink: "https://www.sunway.com.my/careers/",
    eligibility: "Fresh graduates",
    notes: null,
  },

  // ===================== ENERGY / UTILITIES =====================
  {
    title: "TNB Graduate Trainee Programme",
    company: "Tenaga Nasional (TNB)",
    industry: "Oil & Gas",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(17),
    closeDate: daysFromNow(59),
    expectedReopen: null,
    applyLink: "https://www.tnb.com.my/careers",
    eligibility: "Fresh graduates",
    notes: "National electricity utility.",
  },
  {
    title: "PETRONAS Digital Graduate Programme",
    company: "PETRONAS",
    industry: "Big Tech",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-5),
    closeDate: daysFromNow(39),
    expectedReopen: null,
    applyLink: "https://www.petronas.com/careers",
    eligibility: "Fresh graduates (Tech/Data)",
    notes: "Digital & data-focused stream within PETRONAS.",
  },

  // ===================== CAPITAL MARKETS / GOV-LINKED FINANCE =====================
  {
    title: "Bursa Malaysia Graduate Programme",
    company: "Bursa Malaysia",
    industry: "Insurance & Asset Management",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(8)}`,
    applyLink: "https://www.bursamalaysia.com/about_bursa/careers",
    eligibility: "Fresh graduates",
    notes: "National stock exchange.",
  },
  {
    title: "EPF (KWSP) Graduate Programme",
    company: "Employees Provident Fund (EPF)",
    industry: "Insurance & Asset Management",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-38),
    closeDate: daysFromNow(-6),
    expectedReopen: `Expected ${monthName(10)}`,
    applyLink: "https://www.kwsp.gov.my/careers",
    eligibility: "Fresh graduates",
    notes: "One of the world's largest pension funds.",
  },
  {
    title: "Securities Commission Graduate Programme",
    company: "Securities Commission Malaysia",
    industry: "Insurance & Asset Management",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(21),
    closeDate: daysFromNow(63),
    expectedReopen: null,
    applyLink: "https://www.sc.com.my/careers",
    eligibility: "Fresh graduates",
    notes: "Capital markets regulator.",
  },

  // ===================== MEDIA / OTHER MNC =====================
  {
    title: "Astro Management Trainee Programme",
    company: "Astro",
    industry: "Telecommunications",
    roleType: "Management Trainee",
    location: "Bukit Jalil, Kuala Lumpur",
    openDate: daysFromNow(-8),
    closeDate: daysFromNow(34),
    expectedReopen: null,
    applyLink: "https://astro.com.my/careers",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "Petron Management Trainee Programme",
    company: "Petron Malaysia",
    industry: "Oil & Gas",
    roleType: "Management Trainee",
    location: "Kuala Lumpur",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(7)}`,
    applyLink: "https://www.petron.com.my/careers/",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "Maybank Asset Management Graduate",
    company: "Maybank Asset Management",
    industry: "Insurance & Asset Management",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(2),
    closeDate: daysFromNow(45),
    expectedReopen: null,
    applyLink: "https://www.maybank-am.com.my/careers",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "CIMB Fusion / Data Analytics Graduate",
    company: "CIMB",
    industry: "Big Tech",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-6),
    closeDate: daysFromNow(38),
    expectedReopen: null,
    applyLink: "https://www.cimb.com/en/careers.html",
    eligibility: "Fresh graduates (Data/Tech)",
    notes: "Technology & analytics track within CIMB.",
  },
  {
    title: "ZF Malaysia Graduate Programme",
    company: "ZF Group",
    industry: "Big Tech",
    roleType: "Graduate Programme",
    location: "Kulim, Kedah",
    openDate: null,
    closeDate: null,
    expectedReopen: `Expected ${monthName(6)}`,
    applyLink: "https://www.zf.com/careers",
    eligibility: "Fresh graduates (Engineering)",
    notes: null,
  },
  {
    title: "Bank Islam Management Trainee",
    company: "Bank Islam",
    industry: "Management Trainee",
    roleType: "Management Trainee",
    location: "Kuala Lumpur",
    openDate: daysFromNow(16),
    closeDate: daysFromNow(58),
    expectedReopen: null,
    applyLink: "https://www.bankislam.com/careers/",
    eligibility: "Fresh graduates",
    notes: null,
  },
  {
    title: "Telekom Malaysia (TM) Data & AI Graduate",
    company: "Telekom Malaysia (TM)",
    industry: "Big Tech",
    roleType: "Graduate Programme",
    location: "Kuala Lumpur",
    openDate: daysFromNow(-55),
    closeDate: null,
    expectedReopen: null,
    applyLink: "https://www.tm.com.my/careers",
    eligibility: "Fresh graduates (Data/Tech)",
    notes: "Rolling intake.",
  },
];

// ---------------------------------------------------------------------------
// Insert
// ---------------------------------------------------------------------------
async function main() {
  const url = process.env.DATABASE_URL;
  if (!url) {
    console.error(
      "✗ DATABASE_URL is not set.\n" +
        "  Create a .env.local file with your Postgres connection string, e.g.:\n" +
        '  DATABASE_URL="postgresql://user:password@host/dbname?sslmode=require"'
    );
    process.exit(1);
  }

  const pool = new Pool({
    connectionString: url,
    ssl:
      url.includes("sslmode=require") || url.includes("neon.tech")
        ? { rejectUnauthorized: false }
        : undefined,
  });

  await pool.query(`
    CREATE TABLE IF NOT EXISTS programs (
      id             SERIAL PRIMARY KEY,
      title          TEXT NOT NULL,
      company        TEXT NOT NULL,
      industry       TEXT NOT NULL,
      "roleType"     TEXT NOT NULL,
      location       TEXT NOT NULL,
      "openDate"     TEXT,
      "closeDate"    TEXT,
      "expectedReopen" TEXT,
      "applyLink"    TEXT NOT NULL,
      eligibility    TEXT,
      notes          TEXT,
      "createdAt"    TIMESTAMPTZ NOT NULL DEFAULT now(),
      "updatedAt"    TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);

  const existing = (await pool.query(`SELECT COUNT(*)::int AS n FROM programs`))
    .rows[0].n as number;

  if (existing > 0 && !FORCE) {
    console.log(
      `Database already has ${existing} programmes. Use "npm run seed -- --force" to wipe and reload.`
    );
    await pool.end();
    return;
  }

  if (FORCE) await pool.query(`DELETE FROM programs`);

  for (const r of programs) {
    await pool.query(
      `INSERT INTO programs
        (title, company, industry, "roleType", location, "openDate", "closeDate",
         "expectedReopen", "applyLink", eligibility, notes)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,
      [
        r.title,
        r.company,
        r.industry,
        r.roleType,
        r.location ?? "Malaysia",
        r.openDate ?? null,
        r.closeDate ?? null,
        r.expectedReopen ?? null,
        r.applyLink,
        r.eligibility ?? null,
        r.notes ?? null,
      ]
    );
  }

  const total = (await pool.query(`SELECT COUNT(*)::int AS n FROM programs`))
    .rows[0].n as number;
  console.log(
    `✓ Seeded ${programs.length} programmes. Database now has ${total}.`
  );
  await pool.end();
}

main().catch((err) => {
  console.error("✗ Seed failed:", err);
  process.exit(1);
});
